export const ApiTypes = {
    accessProfilesService: 'accessProfilesService',
    addressCountiesService: 'addressCountiesService',
    addressDistrictsService: 'addressDistrictsService',
    addressProvincesService: 'addressProvincesService',
    ageRangeScoreService: 'ageRangeScoreService',
    agentsService: 'agentsService',
    authService: 'authService',
    callsInfoService: 'callsInfoService',
    candidatesService: 'candidatesService',
    candidateJobApplicationsService: 'candidateJobApplicationsService',
    catalogsService: 'catalogsService',
    chatbotQuestionsService: 'chatbotQuestionsService',
    dashboardConfigService: 'dashboardConfigService',
    departmentsService: 'departmentsService',
    employeeAssistancesService: 'employeeAssistancesService',
    employeeTeamsService: 'employeeTeamsService',
    eLibrarySectionService: 'eLibrarySectionService',
    eLibraryDocumentService: 'eLibraryDocumentService',
    healthService: 'healthService',
    hermesCommunicationsService: 'hermesCommunicationsService',
    hermesConfigsService: 'hermesConfigsService',
    interviewAllowedHoursService: 'interviewAllowedHoursService',
    interviewQualificationGradesService: 'interviewQualificationGradesService',
    interviewQualificationGradeItemsService: 'interviewQualificationGradeItemsService',
    meetingRoomReservationService: 'meetingRoomReservationService',
    jobPositionsService: 'jobPositionsService',
    meetingRoomsService: 'meetingRoomsService',
    noteWorkerConfigsService: 'noteWorkerConfigsService',
    platformConfigsService: 'platformConfigsService',
    usersService: 'usersService',
    vacationBalanceService: 'vacationBalanceService',
    emailSenderService:'emailSenderService',
    employeesService: 'employeesService',
};
